from decouple import config

API_BASE_URL = config('API_BASE_URL')
BOT_TOKEN = config('BOT_TOKEN')
PREFIX = config('PREFIX')

CATEGORY = config('CATEGORY')
STEAM_CHANNEL = config('STEAM_CHANNEL')
STEAM_AAA_CHANNEL = config('STEAM_AAA_CHANNEL')
STEAM_DEALS_AMOUNT = int(config('STEAM_DEALS_AMOUNT'))
GOG_CHANNEL = config('GOG_CHANNEL')
GOG_AAA_CHANNEL = config('GOG_AAA_CHANNEL')
GOG_DEALS_AMOUNT = int(config('GOG_DEALS_AMOUNT'))
CHANNELS = [STEAM_CHANNEL, STEAM_AAA_CHANNEL, GOG_CHANNEL, GOG_AAA_CHANNEL]
