from decouple import config

API_BASE_URL = config('API_BASE_URL')
BOT_ROLE_NAME = config('BOT_ROLE_NAME')
BOT_TOKEN = config('BOT_TOKEN')
BOT_TOKEN_DEV = config('BOT_TOKEN_DEV')
PREFIX = config('PREFIX')
PRODUCTION = config('PRODUCTION', default=False, cast=bool)

CATEGORY = config('CATEGORY')
STEAM_CHANNEL = config('STEAM_CHANNEL')
STEAM_AAA_CHANNEL = config('STEAM_AAA_CHANNEL')
GOG_CHANNEL = config('GOG_CHANNEL')
GOG_AAA_CHANNEL = config('GOG_AAA_CHANNEL')
CHANNELS = [STEAM_CHANNEL, STEAM_AAA_CHANNEL, GOG_CHANNEL, GOG_AAA_CHANNEL]
